server:
  port: ${SERVER_PORT:8080}

origin:
  allowed: ${ALLOWED_ORIGIN:http://localhost:3000}

spring:
  profiles:
    active: ${SPRING_PROFILE:local}
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 2MB
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI:{baseUrl}/v1/oauth2/callback/{registrationId}}
            scope:
              - email

jwt:
  access-secret-key-base64: ${JWT_ACCESS_SECRET_KEY_BASE64:iAbBnFDrPJgglJr+yO0dC1qITxoCJcm1HB8ZiFWhtN19lWOdCaiPmvqXRTLmqe4cIdaT5X62swd/8lfp8rdw0Q==}
  access-expiration-seconds: ${JWT_ACCESS_EXPIRATION_SECONDS:43200}
  refresh-secret-key-base64: ${JWT_REFRESH_SECRET_KEY_BASE64:zxY3hKXBd6MPmmxha1rwte7GayIdjuzOTeD6nyuO7MockdamStat6G0nDF2T8EJP041sdz4eZxEPNJEGIXGmiQ==}
  refresh-expiration-seconds: ${JWT_REFRESH_EXPIRATION_SECONDS:8640000}

s3:
  access-key-id: ${S3_ACCESS_KEY_ID}
  secret-access-key: ${S3_SECRET_ACCESS_KEY}
  region: ${S3_REGION}
  bucket: ${S3_BUCKET}
  endpoint: ${S3_ENDPOINT:https://dcfbfd9f489ad8a785c3cdb81469e07d.r2.cloudflarestorage.com}
  public-base-url: ${S3_PUBLIC_BASE_URL}

---

spring:
  config:
    activate:
      on-profile: ssl

server:
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEY_STORE_PASSWORD}
